### ISSUE TITLE
Could not pass event InventoryCloseEvent to ChestSort v1.7.3

### ISSUE THREAD

**Issue by bshuler** [JEFF-Media-GbR/Spigot-ChestSort#1]
[20:15:07 ERROR]: Could not pass event InventoryCloseEvent to ChestSort v1.7.3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigotmc-1.13-R0.1.jar:git-Spigot-0b44fa0-49a2604]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigotmc-1.13-R0.1.jar:git-Spigot-0b44fa0-49a2604]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigotmc-1.13-R0.1.jar:git-Spigot-0b44fa0-49a2604]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigotmc-1.13-R0.1.jar:git-Spigot-0b44fa0-49a2604]
        at org.bukkit.craftbukkit.v1_13_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:888) ~[spigotmc-1.13-R0.1.jar:git-Spigot-0b44fa0-49a2604]
        at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1910) ~[spigotmc-1.13-R0.1.jar:git-Spigot-0b44fa0-49a2604]
        at net.minecraft.server.v1_13_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) ~[spigotmc-1.13-R0.1.jar:git-Spigot-0b44fa0-49a2604]
        at net.minecraft.server.v1_13_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:1) ~[spigotmc-1.13-R0.1.jar:git-Spigot-0b44fa0-49a2604]
        at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigotmc-1.13-R0.1.jar:git-Spigot-0b44fa0-49a2604]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigotmc-1.13-R0.1.jar:git-Spigot-0b44fa0-49a2604]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigotmc-1.13-R0.1.jar:git-Spigot-0b44fa0-49a2604]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigotmc-1.13-R0.1.jar:git-Spigot-0b44fa0-49a2604]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigotmc-1.13-R0.1.jar:git-Spigot-0b44fa0-49a2604]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigotmc-1.13-R0.1.jar:git-Spigot-0b44fa0-49a2604]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at de.jeffclan.JeffChestSort.JeffChestSortPlugin.sortingEnabled(JeffChestSortPlugin.java:58) ~[?:?]
        at de.jeffclan.JeffChestSort.JeffChestSortListener.onInventoryClose(JeffChestSortListener.java:88) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor325.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigotmc-1.13-R0.1.jar:git-Spigot-0b44fa0-49a2604]
        ... 16 more

**Comment by mfnalex** [comment]
Thanks your help improving ChestSort :) First of all, please post the following information:
- Version of spigot / Minecraft
- List of all installed plugins

Please try again with the newest of ChestSort available at spigotmc.org (1.7.4.1). If the error happens again, please tell me what exactly you did. Did you just open a chest? Does it happen with all chests?

Thank you for troubleshooting :)

**Comment by mfnalex** [comment]
I forgot to mention: After installing the latest version of ChestSort, please shutdown your server, delete the ChestSort folder under plugins/ and then restart your server using the latest spigot version.

**Comment by mfnalex** [comment]
It seems that you used /reload to reload your server and plugins. This is not supported and very bad practice. You should always shutdown the server and then start it again instead of using /reload.

Spigot even prints a warning when you are using /reload:

> Please note that this command is not supported and may cause issues[...]

**Comment by mfnalex** [comment]
The newest version includes a fix that will make the plugin survive using /reload. Thanks for the inspiration
